"""contadores de estado nos checks

Revision ID: 46e220d5a5c2
Revises: 303c24123cde
Create Date: 2026-09-09 15:09:29.646265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e220d5a5c2'
down_revision: Union[str, None] = '303c24123cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('consecutive_successes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('checks', sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'consecutive_failures')
    op.drop_column('checks', 'consecutive_successes')
    # ### end Alembic commands ###
