"""backup de ativos

Revision ID: a1c4f9b3d7e2
Revises: f7f0da26594a
Create Date: 2026-09-09 22:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c4f9b3d7e2'
down_revision: Union[str, None] = 'f7f0da26594a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('backup_notes', sa.Text(), nullable=True))
    op.add_column(
        'asset_photos',
        sa.Column('category', sa.String(length=20), nullable=False, server_default='general'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_photos', 'category')
    op.drop_column('assets', 'backup_notes')
    # ### end Alembic commands ###
