"""credenciais de acesso do ativo

Revision ID: b2e6a1f4c9d3
Revises: a1c4f9b3d7e2
Create Date: 2026-09-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a7c2e819f6'
down_revision: Union[str, None] = 'c3f6a9d02e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('credential_username', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('credential_password_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'credential_password_encrypted')
    op.drop_column('assets', 'credential_username')
    # ### end Alembic commands ###
