"""status_since nos ativos

Revision ID: f7f0da26594a
Revises: 46e220d5a5c2
Create Date: 2026-09-09 15:20:26.100229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f0da26594a'
down_revision: Union[str, None] = '46e220d5a5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('status_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'status_since')
    # ### end Alembic commands ###
